services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: bot
    image: kudoser/steam-together-bot:${GIT_COMMIT:-latest}
    healthcheck:
      test: curl -fsSI http://localhost:${BOT_HEALTHCHECK__PORT:?} || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    environment:
      - BOT_TELEGRAM__TOKEN=${BOT_TELEGRAM__TOKEN}
      - BOT_STEAM__APIKEY=${BOT_STEAM__APIKEY}
      - BOT_DATABASE__CONNECTIONSTRING=Data Source=/data/database.db
      - BOT_HEALTHCHECK__PORT=${BOT_HEALTHCHECK__PORT:?}
    volumes:
      - data:/data

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
      target: scraper
    image: kudoser/steam-together-scraper:${GIT_COMMIT:-latest}
    depends_on:
      - bot
    environment:
      - SCRAPER_STEAM__APIKEY=${SCRAPER_STEAM__APIKEY}
      - SCRAPER_DATABASE__CONNECTIONSTRING=Data Source=/data/database.db
      - SCRAPER_SCRAPER__RUNONSTARTUP=true
      - BOT_HEALTHCHECK_URL=http://bot:${BOT_HEALTHCHECK__PORT:?}
    volumes:
      - data:/data

volumes:
  data:
