// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamTogether.Bot.Context;

#nullable disable

namespace SteamTogether.Bot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230401020618_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("SteamTogether.Bot.Models.SteamPlayer", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("SteamPlayers");

                    b.HasData(
                        new
                        {
                            PlayerId = "76561198068819558"
                        },
                        new
                        {
                            PlayerId = "zebradil"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
