name: Deploy to Production

on:
  push:
    branches:
      - master
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.sln"
      - "*/appsettings.*.json"
      - ".dockerignore"
      - ".github/workflows/deploy.yaml"
      - "Dockerfile"
      - "compose.yaml"
      - "docker/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ADDITIONAL_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Write SSH key to file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOCKER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Generate version number
        id: version
        run: |
          TAG=$(git describe --abbrev=0 --tags 2>/dev/null)
          if [ -n "$TAG" ] && git describe --exact-match &>/dev/null; then
              VERSION=$TAG
          else
              SHORT_SHA=$(git rev-parse --short HEAD)
              if [ -z "$TAG" ]; then
                  COMMITS_SINCE_BEGINNING=$(git rev-list --count HEAD 2>/dev/null)
                  VERSION="0.0.0.$COMMITS_SINCE_BEGINNING-$SHORT_SHA"
              else
                  COMMITS_SINCE_TAG=$(git rev-list --count HEAD ^$TAG 2>/dev/null)
                  VERSION="$TAG.$COMMITS_SINCE_TAG-$SHORT_SHA"
              fi
          fi
          echo "::set-output name=version::$VERSION"

      - name: Docker Compose build
        run: docker compose build --build-arg VERSION=${{ steps.version.outputs.version }}
        env:
          DOCKER_HOST: "${{ secrets.DOCKER_HOST }}"
          GIT_COMMIT: ${{ github.sha }}
          BOT_HEALTHCHECK__PORT: 10090

      - name: Docker Compose up
        run: docker compose up -d
        env:
          BOT_STEAM__APIKEY: ${{ secrets.STEAM_APIKEY }}
          BOT_TELEGRAM__TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DOCKER_HOST: "${{ secrets.DOCKER_HOST }}"
          GIT_COMMIT: ${{ github.sha }}
          SCRAPER_STEAM__APIKEY: ${{ secrets.STEAM_APIKEY }}
          BOT_HEALTHCHECK__PORT: 10090

      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🚀 *New deployment* 🚀
            Commit: [${{ github.sha }}](${{ github.event.head_commit.url }})
            Commit message: `${{ github.event.head_commit.message }}`
            Author: `${{ github.event.head_commit.author.name }}`
            [Compare changes](${{ github.event.compare }})
