name: Deploy to Production

on:
  push:
    branches:
      - master
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.sln"
      - "*/appsettings.*.json"
      - ".dockerignore"
      - ".github/workflows/deploy.yaml"
      - "Dockerfile"
      - "compose.yaml"
      - "docker/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ADDITIONAL_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Write SSH key to file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOCKER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Docker Compose build
        run: docker compose build
        env:
          DOCKER_HOST: "${{ secrets.DOCKER_HOST }}"
          GIT_COMMIT: ${{ github.sha }}

      - name: Docker Compose up
        run: docker compose up -d
        env:
          BOT_STEAM__APIKEY: ${{ secrets.STEAM_APIKEY }}
          BOT_TELEGRAM__TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DOCKER_HOST: "${{ secrets.DOCKER_HOST }}"
          GIT_COMMIT: ${{ github.sha }}
          SCRAPER_STEAM__APIKEY: ${{ secrets.STEAM_APIKEY }}

      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🚀 *New deployment* 🚀
            Commit: [${{ github.sha }}](${{ github.event.head_commit.url }})
            Commit message: `${{ github.event.head_commit.message }}`
            Author: `${{ github.event.head_commit.author.name }}`
            [Compare changes](${{ github.event.compare }})
