name: .NET

on:
  push:
    branches: ["master"]
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.sln"
      - ".github/workflows/dotnet.yaml"
  pull_request:
    branches: ["*"]
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.sln"
      - ".github/workflows/dotnet.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Restore Dev Dependencies
        run: dotnet tool restore

      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Merge Coverage Reports
        run: dotnet coverage merge 'coverage/*.cobertura.xml' --recursive --output merged.cobertura.xml --output-format cobertura

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: merged.cobertura.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
