name: Renovate

on:
  workflow_dispatch:
  schedule:
    # Run every day at 8:00 UTC
    - cron: '0 8 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions: write-all
      # actions: write
      # contents: write
      # issues: write
      # pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.0.2
        with:
          configurationFile: .github/selfhosted-renovate.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
